#!/usr/bin/env bash
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"
export SENECHAL_SKIP_CONFIG_CHECK=1
PASS=0; FAIL=0
ok()  { printf '  ok   %s\n' "$1"; PASS=$((PASS + 1)); }
bad() { printf '  FAIL %s\n' "$1"; FAIL=$((FAIL + 1)); }
check(){ [ "$2" = "$3" ] && ok "$1" || bad "$1 (got '$2', want '$3')"; }

T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT

mkdir -p "$T/live" "$T/bin"
cat > "$T/bin/crontab" <<'SH'
#!/usr/bin/env bash
[ "$1" = -l ] && [ "$2" = -u ] || exit 2
cat "$T_LIVE/$3" 2>/dev/null
exit 0
SH
chmod +x "$T/bin/crontab"
export PATH="$T/bin:$PATH" T_LIVE="$T/live"
export SENECHAL_SUDO_CMD=""

RUNNER_LINE='7 * * * * PACED_MAX_PER_TICK=1 /home/acct1/Documents/Projects/scheduler/bin/usage-paced-runner.sh # scheduler:scheduler-paced-runner:RUNNER (usage-paced dispatch)'
printf '%s\n' "$RUNNER_LINE" > "$T/live/acct1"
printf '%s\n' "$RUNNER_LINE" > "$T/live/acct2"

run() { SENECHAL_CRONTAB_PARK_DIR="$T/park" ./crontab-park-armed-cleanup.sh "$@"; }

echo "-- A. no park directory at all"
rm -rf "$T/park"
out="$(run verify -q)"; rc=$?
check "A1 verify passes when the directory is already gone" "$rc" "0"
out="$(run enable)"; rc=$?
check "A2 enable is a no-op when the directory is already gone" "$rc" "0"

echo "-- B. a redundant park (markers-only diff, #558's actual finding)"
mkdir -p "$T/park"
{ printf '# >>> scheduler-managed (generated by bin/sync-crontab.sh) >>>\n'
  printf '# <<< scheduler-managed <<<\n'
  printf '%s\n' "$RUNNER_LINE"; } > "$T/park/acct1.cron"
printf '%s\n' "$RUNNER_LINE" > "$T/park/acct2.cron"

out="$(run verify -q)"; rc=$?
check "B1 verify fails while the redundant directory still exists" "$rc" "5"
printf '%s' "$out" | grep -q "run: ./crontab-park-armed-cleanup.sh enable" \
  && ok "B2 verify names the fix" || bad "B2 verify did not name the fix ($out)"

out="$(run enable)"; rc=$?
check "B3 enable exits 0 against a redundant park" "$rc" "0"
[ -d "$T/park" ] && bad "B4 enable actually removed the directory" || ok "B4 enable actually removed the directory"

out="$(run verify -q)"; rc=$?
check "B5 verify passes after enable removed it" "$rc" "0"

echo "-- C. a park that is NOT redundant -- refuses to delete"
mkdir -p "$T/park"
printf '%s\nSOMETHING NOT ON THE LIVE CRONTAB\n' "$RUNNER_LINE" > "$T/park/acct1.cron"

out="$(run verify -q)"; rc=$?
check "C1 verify fails on a non-redundant park" "$rc" "5"
printf '%s' "$out" | grep -qi "needs a human look" \
  && ok "C2 verify distinguishes this from the safe-to-delete case" || bad "C2 wrong verify message ($out)"

out="$(run enable 2>&1)"; rc=$?
check "C3 enable REFUSES a non-redundant park" "$rc" "1"
[ -d "$T/park" ] && ok "C4 enable left the directory alone" || bad "C4 enable deleted a non-redundant directory"

echo "crontab-park-armed-cleanup test: $PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ]
