#!/usr/bin/env bash
# senechal: closing the lid should suspend -- UNLESS Claude is working.
#
#   ./lid-inhibit-honoured.sh enable    # PowerDevil blanks the screen; this daemon owns suspend
#   ./lid-inhibit-honoured.sh verify    # non-AI, cron-safe: did lid closes actually obey?
#   [rest: vault:senechal/header-archaeology-20260818.md]
set -uo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"
# shellcheck source=../lib/common.sh
. ../lib/common.sh

# --- target values, defined once, read by every verb --------------------
CONF_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/lid-inhibit"
PATTERNS_FILE="$CONF_DIR/patterns.conf"
EXCLUDES_FILE="$CONF_DIR/excludes.conf"
DAEMON="$HOME/.local/bin/lid-inhibit-daemon"
WATCHER="$HOME/.local/bin/lid-inhibit-watch"
UNIT_DIR="${SENECHAL_LID_UNIT_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user}"
UNIT_NAME="lid-inhibit-daemon.service"
KDE_PROFILES="${XDG_CONFIG_HOME:-$HOME/.config}/powermanagementprofilesrc"
# PowerDevil HandleButtonEvents action codes. 64 = "Turn off screen" is
# what we want the lid to do; 1 = "Sleep" is the KDE default `disable`
# puts back. 0 ("Do nothing") is attempt 1 and must never be written.
LID_ACTION_BLANK=64
LID_ACTION_SLEEP=1
KDE_PROFILE_SECTIONS="AC Battery LowBattery"
# $USER is unset under some non-login/cron invocations; the advisory text
# below needs a real username regardless.
TARGET_USER="${USER:-$(id -un)}"
# KDE's own idle-autosuspend defaults, restored by `disable`. Read off
# this machine's file before it was changed, per profile.
suspend_default_idle() { # $1 = profile section
  case "$1" in
    AC)         echo 900000 ;;
    Battery)    echo 600000 ;;
    LowBattery) echo 300000 ;;
    *)          echo 600000 ;;
  esac
}

# Test-mode escape hatch: lets `enable` run against a throwaway HOME with
# no live systemd and no session bus. Same shape as estate-health-timer.
LIVE=1
[ -z "${SENECHAL_LID_UNIT_DIR:-}" ] || LIVE=0

# Processes that match a watch pattern but are NOT a working session.
# Claude Code's daemon pool is the whole reason this file exists: on
# 2026-08-06, 15 processes matched `claude` and 10 were that idle pool,
# so the watch was satisfied forever and the lid never slept.
EXCLUDES_DEFAULT='# One ERE per line. A process matching a watch pattern is IGNORED if its
# command line also matches any line here. Without this the watch never
# turns off -- see the header of remedies/lid-inhibit-honoured.sh.
bg-spare
bg-pty-host
cc-daemon-
lid-inhibit
shell-snapshots'

# --- generated files ----------------------------------------------------
# All three are written by `enable` and byte-compared by `verify`, so the
# two verbs can never disagree about what "installed" means.

watcher_content() {
  cat <<'PYEOF'
#!/usr/bin/env python3
# GENERATED by senechal remedies/lid-inhibit-honoured.sh -- edit there, re-run enable.
#
# Owns the lid. PowerDevil is configured to do nothing but blank the
#   [rest: vault:senechal/header-archaeology-20260818.md]
import os, subprocess, sys, select, struct, time

MATCH_CMD = [os.path.expanduser("~/.local/bin/lid-inhibit-daemon"), "--match"]
SOUND_HELD = "dialog-warning"    # sharp, insistent: NOT going to sleep
SOUND_SLEEP = "service-logout"   # descending: going down now
# Long enough to reopen the lid and cancel, short enough not to feel
# broken. Also re-checks the watch, so a Claude run that starts in this
# window cancels the suspend rather than being cut off by it.
GRACE_SEC = 4

EV_SW, SW_LID = 0x05, 0x00
EVENT_SIZE = struct.calcsize("llHHi")
DEVNULL = subprocess.DEVNULL


def log(msg):
    print("lid-inhibit: " + msg, file=sys.stderr, flush=True)


def lid_device():
    # Blocks look like:
    #   N: Name="Lid Switch"
    #   H: Handlers=event0
    # The handler is "Handlers=event0", NOT a bare "event0" token -- an
    #   [rest: vault:senechal/header-archaeology-20260818.md]
    def handler_of(block):
        for line in block.splitlines():
            if line.startswith("H:") and "Handlers=" in line:
                for tok in line.split("Handlers=", 1)[1].split():
                    if tok.startswith("event"):
                        return "/dev/input/" + tok
        return None
    try:
        with open("/proc/bus/input/devices") as fh:
            block = ""
            for line in fh:
                if line.strip() == "":
                    if '"Lid Switch"' in block:
                        return handler_of(block)
                    block = ""
                else:
                    block += line
            if '"Lid Switch"' in block:
                return handler_of(block)
    except OSError:
        pass
    return None


def open_lid():
    path = lid_device()
    if not path:
        log("no evdev Lid Switch found")
        return None
    try:
        return os.open(path, os.O_RDONLY | os.O_NONBLOCK)
    except PermissionError:
        log("%s unreadable -- need group 'input' (sudo usermod -aG input $USER)" % path)
    except OSError as e:
        log("%s: %s" % (path, e))
    return None


def play(name):
    for cmd in (["canberra-gtk-play", "-i", name],
                ["paplay", "/usr/share/sounds/freedesktop/stereo/%s.oga" % name]):
        try:
            if subprocess.call(cmd, stdout=DEVNULL, stderr=DEVNULL) == 0:
                return
        except OSError:
            continue
    sys.stdout.write("\a")
    sys.stdout.flush()


def watched():
    return subprocess.call(MATCH_CMD, stdout=DEVNULL) == 0


def lid_events(fd):
    # Returns the switch values seen: 1 = closed, 0 = opened.
    try:
        data = os.read(fd, EVENT_SIZE * 16)
    except BlockingIOError:
        return []
    out = []
    for i in range(0, len(data) - EVENT_SIZE + 1, EVENT_SIZE):
        _, _, etype, code, value = struct.unpack("llHHi", data[i:i + EVENT_SIZE])
        if etype == EV_SW and code == SW_LID:
            out.append(value)
    return out


def reopened_within(fd, seconds):
    deadline = time.monotonic() + seconds
    while True:
        timeout = deadline - time.monotonic()
        if timeout <= 0:
            return False
        r, _, _ = select.select([fd], [], [], timeout)
        if r and 0 in lid_events(fd):
            return True


def on_close(fd):
    if watched():
        log("lid closed, watch ACTIVE -- staying awake")
        play(SOUND_HELD)
        return
    log("lid closed, watch quiet -- suspending in %ds" % GRACE_SEC)
    play(SOUND_SLEEP)
    if reopened_within(fd, GRACE_SEC):
        log("lid reopened during the grace window -- suspend cancelled")
        return
    if watched():
        log("watch became active during the grace window -- suspend cancelled")
        return
    log("suspending now")
    if subprocess.call(["systemctl", "suspend"]) != 0:
        log("systemctl suspend FAILED -- the machine is awake with the lid shut")


def main():
    fd = open_lid()
    if fd is None:
        # Loud, not silent. With no readable lid switch this daemon
        # cannot decide anything, and PowerDevil has already been told
        # not to suspend -- so failing quietly here would mean a machine
        # that never sleeps, which is exactly attempt 1's bug.
        log("cannot read the lid switch, so nothing would ever suspend -- refusing to run")
        return 1
    log("watching the lid; PowerDevil blanks the screen, this daemon decides suspend")
    try:
        while True:
            select.select([fd], [], [], None)
            for value in lid_events(fd):
                if value == 1:
                    on_close(fd)
    finally:
        os.close(fd)


if __name__ == "__main__":
    sys.exit(main())
PYEOF
}

daemon_content() {
  cat <<EOF
#!/usr/bin/env bash
# GENERATED by senechal remedies/lid-inhibit-honoured.sh -- edit there, re-run enable.
#
#   lid-inhibit-daemon --match    exit 0 if a watched process is running
#   [rest: vault:senechal/header-archaeology-20260818.md]
set -uo pipefail

PATTERNS="\$HOME/.config/lid-inhibit/patterns.conf"
EXCLUDES="\$HOME/.config/lid-inhibit/excludes.conf"

excluded() { # \$1 = a full \`pgrep -af\` line
  local e
  [ -r "\$EXCLUDES" ] || return 1
  while IFS= read -r e; do
    [[ -z "\$e" || "\$e" == \\#* ]] && continue
    [[ "\$1" =~ \$e ]] && return 0
  done < "\$EXCLUDES"
  return 1
}

any_match() {
  local p line
  [ -r "\$PATTERNS" ] || return 1
  while IFS= read -r p; do
    [[ -z "\$p" || "\$p" == \\#* ]] && continue
    while IFS= read -r line; do
      [ -n "\$line" ] || continue
      # Never let this daemon's own command line satisfy its own watch.
      [ "\${line%% *}" = "\$\$" ] && continue
      excluded "\$line" && continue
      return 0
    done < <(pgrep -af "\$p" 2>/dev/null)
  done < "\$PATTERNS"
  return 1
}

case "\${1:-}" in
  --match) any_match; exit \$? ;;
  *) echo "usage: \$(basename "\$0") --match" >&2; exit 2 ;;
esac
EOF
}

unit_content() {
  cat <<EOF
[Unit]
Description=Lid owner: blank via PowerDevil, suspend decided by the watch

[Service]
ExecStart=$WATCHER
# on-failure, NOT always: an unreadable lid switch is a permanent fault
# (group 'input'), and retrying it forever would hide it. Five tries then
# 'failed', where systemctl --user status shows it.
Restart=on-failure

[Install]
WantedBy=default.target
EOF
}

# --- shared config readers/writers, used by enable, disable and verify --
# Deliberately not lib's ini_set: that matches a key file-wide and
# rewrites every occurrence, so setting three profiles to three different
# values -- which these verbs do -- would silently give all three the
# last value written. All three are idempotent and leave every other key
# in the file alone.

kde_get() { # $1 = full section header e.g. "[AC][HandleButtonEvents]", $2 = key
  [ -r "$KDE_PROFILES" ] || return 1
  awk -v want="$1" -v key="$2" '
    $0 == want { inside = 1; next }
    /^\[/      { inside = 0 }
    inside && index($0, key "=") == 1 { sub("^" key "=", ""); print; exit }
  ' "$KDE_PROFILES"
}

kde_set() { # $1 = full section header, $2 = key, $3 = value
  local section="$1" key="$2" value="$3" tmp
  [ -f "$KDE_PROFILES" ] || return 1
  tmp="$(mktemp)" || return 1
  awk -v want="$section" -v key="$key" -v val="$value" '
    BEGIN { inside = 0; done = 0 }
    $0 == want { inside = 1; print; next }
    /^\[/ {
      if (inside && !done) { print key "=" val; done = 1 }
      inside = 0; print; next
    }
    inside && index($0, key "=") == 1 { print key "=" val; done = 1; next }
    { print }
    END { if (inside && !done) print key "=" val }
  ' "$KDE_PROFILES" > "$tmp" || { rm -f "$tmp"; return 1; }
  # The section may not exist at all yet (a profile never customised).
  if ! grep -qF "$section" "$tmp"; then
    printf '\n%s\n%s=%s\n' "$section" "$key" "$value" >> "$tmp"
  fi
  cat "$tmp" > "$KDE_PROFILES" && rm -f "$tmp"
}

# Removing the whole group is how KDE itself expresses "this action is
# off" -- SuspendSession has no "Do nothing" value (confirmed from
# powerdevilsuspendsessionaction_config.so: Sleep / Hybrid sleep /
# Shut down / Lock screen only), it is a checkbox, and an unchecked box
# writes no group.
kde_del_group() { # $1 = full section header
  local section="$1" tmp
  [ -f "$KDE_PROFILES" ] || return 1
  grep -qF "$section" "$KDE_PROFILES" || return 0
  tmp="$(mktemp)" || return 1
  awk -v want="$section" '
    $0 == want { inside = 1; next }
    /^\[/      { inside = 0 }
    !inside    { print }
  ' "$KDE_PROFILES" > "$tmp" || { rm -f "$tmp"; return 1; }
  cat "$tmp" > "$KDE_PROFILES" && rm -f "$tmp"
}

kde_has_group() { # $1 = full section header
  [ -r "$KDE_PROFILES" ] && grep -qF "$1" "$KDE_PROFILES"
}

install_file() { # $1 dest, $2 mode, content on stdin
  local dest="$1" mode="$2" content b
  content="$(cat)"
  if [ -f "$dest" ] && [ "$(cat "$dest" 2>/dev/null)" = "$content" ]; then
    say "  $dest -- already correct, untouched"
    chmod "$mode" "$dest"
    return 0
  fi
  b="$(backup_file "$dest")" && [ -n "$b" ] && say "  backed up old $dest -> $b"
  mkdir -p "$(dirname "$dest")" || die "could not create $(dirname "$dest")"
  printf '%s\n' "$content" > "$dest" || die "could not write $dest"
  chmod "$mode" "$dest"
  say "  wrote $dest"
}

# Both enable and disable rewrite the same file; the backup is taken once,
# lazily, on the first real change, so a re-run that alters nothing does
# not litter a fresh backup directory.
PROFILES_BACKED_UP=0
backup_profiles_once() {
  [ "$PROFILES_BACKED_UP" -eq 1 ] && return 0
  local b
  b="$(backup_file "$KDE_PROFILES")" && [ -n "$b" ] && say "  backed up $KDE_PROFILES -> $b"
  PROFILES_BACKED_UP=1
}

# PowerDevil caches its button-event policy at process start, not per
# reparse -- confirmed live 2026-08-10 (hf7y/senechal#169): the D-Bus
# reparse fires and PowerDevil even emits configurationReloaded(), but a
# lid close still ran the OLD lidAction. So the config change is only
# real after a fresh process.
powerdevil_reload() {
  [ "$LIVE" -eq 1 ] || return 0
  gdbus call --session --dest org.kde.Solid.PowerManagement \
    --object-path /org/kde/Solid/PowerManagement \
    --method org.kde.Solid.PowerManagement.reparseConfiguration >/dev/null 2>&1 \
    && say "  told PowerDevil to reparse its config" \
    || warn "could not reach PowerDevil to reparse -- log out and back in"
  if systemctl --user restart plasma-powerdevil.service >/dev/null 2>&1; then
    say "  restarted plasma-powerdevil.service so it starts fresh with the new config"
  else
    warn "could not restart plasma-powerdevil.service -- log out and back in, or PowerDevil may still be running the stale cached policy"
  fi
}

# --- enable -------------------------------------------------------------
enable_() {
  say "lid-inhibit-honoured enable: this daemon owns the lid; PowerDevil only blanks the screen"
  say ""

  # Checked FIRST, before anything is written, so a refusal leaves the
  # machine exactly as it was rather than half-applied.
  #
  # $KDE_PROFILES has a second writer: System Settings' power KCM holds
  #   [rest: vault:senechal/header-archaeology-20260818.md]
  if [ "$LIVE" -eq 1 ] && pgrep -f 'systemsettings.*powerdevil' >/dev/null 2>&1; then
    die "System Settings is open on the Power Management page (pid $(pgrep -f 'systemsettings.*powerdevil' | head -1)).
    It rewrites $KDE_PROFILES wholesale on save, which would silently revert
    steps 3 and 4 below. Nothing has been changed. Close that window and re-run."
  fi

  say "1. watch list"
  mkdir -p "$CONF_DIR" || die "could not create $CONF_DIR"
  if [ ! -f "$PATTERNS_FILE" ]; then
    printf '%s\n' '# One pgrep -f pattern per line -- lid stays awake while any process matches' 'claude' \
      > "$PATTERNS_FILE" || die "could not write $PATTERNS_FILE"
    say "  wrote $PATTERNS_FILE (default: claude)"
  else
    say "  $PATTERNS_FILE -- kept as-is ($(grep -cvE '^\s*#|^\s*$' "$PATTERNS_FILE") pattern(s))"
  fi
  printf '%s\n' "$EXCLUDES_DEFAULT" | install_file "$EXCLUDES_FILE" 0644

  say ""
  say "2. daemon"
  watcher_content | install_file "$WATCHER" 0755
  daemon_content  | install_file "$DAEMON" 0755
  unit_content    | install_file "$UNIT_DIR/$UNIT_NAME" 0644

  say ""
  say "3. the lid only blanks the screen (PowerDevil never suspends it)"
  if [ -f "$KDE_PROFILES" ]; then
    local section before
    for section in $KDE_PROFILE_SECTIONS; do
      before="$(kde_get "[$section][HandleButtonEvents]" lidAction)"
      if [ "$before" = "$LID_ACTION_BLANK" ]; then
        say "  [$section] lidAction already $LID_ACTION_BLANK (turn off screen)"
      else
        backup_profiles_once
        kde_set "[$section][HandleButtonEvents]" lidAction "$LID_ACTION_BLANK" \
          || die "could not rewrite $KDE_PROFILES"
        say "  [$section] lidAction ${before:-<unset>} -> $LID_ACTION_BLANK (turn off screen)"
      fi
    done

    say ""
    say "4. idle autosuspend off (Zach-directed: the daemon is the only suspender)"
    for section in $KDE_PROFILE_SECTIONS; do
      if kde_has_group "[$section][SuspendSession]"; then
        backup_profiles_once
        kde_del_group "[$section][SuspendSession]" || die "could not rewrite $KDE_PROFILES"
        say "  [$section] SuspendSession removed -- no idle autosuspend"
      else
        say "  [$section] SuspendSession already absent"
      fi
    done

    [ "$PROFILES_BACKED_UP" -eq 1 ] && powerdevil_reload
  else
    warn "$KDE_PROFILES absent -- skipping the KDE half (not a KDE session?)"
  fi

  say ""
  say "5. start the daemon"
  if [ "$LIVE" -eq 1 ]; then
    systemctl --user daemon-reload || die "daemon-reload failed"
    systemctl --user enable --now "$UNIT_NAME" || die "could not enable $UNIT_NAME"
    systemctl --user restart "$UNIT_NAME" || die "could not restart $UNIT_NAME"
    say "  $UNIT_NAME restarted"
  else
    say "  (test mode: skipped daemon-reload / enable / restart)"
  fi

  say ""
  say "WHAT THIS SCRIPT COULD NOT DO FOR YOU"
  say ""
  if id -nG 2>/dev/null | tr ' ' '\n' | grep -qx input; then
    say "  * nothing for the lid switch -- you are already in group 'input'."
  else
    say "  * GROUP 'input' IS REQUIRED, not optional. This daemon reads the"
    say "    lid switch to decide at all, and PowerDevil has already been"
    say "    told not to suspend -- so without it NOTHING suspends:"
    say "        sudo usermod -aG input $TARGET_USER"
    say "    then log out and back in. Until then the unit fails loudly"
    say "    rather than pretending to work:"
    say "        systemctl --user status $UNIT_NAME"
  fi
  say ""
  say "  * TWO LID CLOSES, BY HAND. Nothing above is evidence. Close the"
  say "    lid ~15s with Claude running -- you should hear the SHARP beep"
  say "    and find it awake. Then close it with nothing running -- you"
  say "    should hear the DESCENDING beep and it should suspend. Then:"
  say "        ./lid-inhibit-honoured.sh verify"
}

# --- disable ------------------------------------------------------------
disable_() {
  say "lid-inhibit-honoured disable: giving the lid back to PowerDevil"
  if [ "$LIVE" -eq 1 ]; then
    systemctl --user disable --now "$UNIT_NAME" 2>/dev/null || say "  (unit was not enabled)"
    say "  $UNIT_NAME stopped and disabled"
  fi

  # Unlike the previous version, disable MUST put the KDE config back:
  # lidAction=64 and the missing SuspendSession groups are not defaults,
  # and leaving them would mean a machine that never suspends once the
  # daemon is gone -- attempt 1's bug, reached by the back door.
  if [ -f "$KDE_PROFILES" ]; then
    local section before
    for section in $KDE_PROFILE_SECTIONS; do
      before="$(kde_get "[$section][HandleButtonEvents]" lidAction)"
      if [ "$before" = "$LID_ACTION_SLEEP" ]; then
        say "  [$section] lidAction already $LID_ACTION_SLEEP (sleep)"
      else
        backup_profiles_once
        kde_set "[$section][HandleButtonEvents]" lidAction "$LID_ACTION_SLEEP" \
          || die "could not rewrite $KDE_PROFILES"
        say "  [$section] lidAction ${before:-<unset>} -> $LID_ACTION_SLEEP (sleep)"
      fi
      if kde_has_group "[$section][SuspendSession]"; then
        say "  [$section] SuspendSession already present"
      else
        backup_profiles_once
        kde_set "[$section][SuspendSession]" idleTime "$(suspend_default_idle "$section")" \
          || die "could not rewrite $KDE_PROFILES"
        kde_set "[$section][SuspendSession]" suspendType "$LID_ACTION_SLEEP" \
          || die "could not rewrite $KDE_PROFILES"
        say "  [$section] SuspendSession restored to the KDE default ($(suspend_default_idle "$section")ms -> sleep)"
      fi
    done
    [ "$PROFILES_BACKED_UP" -eq 1 ] && powerdevil_reload
    say ""
    say "  NOTE: restored to KDE DEFAULTS, not to whatever you had before."
    say "  Your pre-enable file is in the newest ~/.senechal-remedy-backups/*."
  fi
  say ""
  say "Done. $WATCHER and $DAEMON left in place; delete them by hand if you want them gone."
}

# --- verify -------------------------------------------------------------
# The evidence half. Everything above the OUTCOMES block is necessary and
# not sufficient: attempt 2 passed every installation check while
# suspending mid-Claude.
verify_() {
  head_ "lid-inhibit-honoured: the lid blanks; this daemon alone decides suspend"

  local installed=1
  local f
  for f in "$WATCHER" "$DAEMON" "$UNIT_DIR/$UNIT_NAME"; do
    [ -f "$f" ] || { fail "$f missing -- run enable"; installed=0; }
  done
  if [ "$installed" -eq 1 ]; then
    if [ "$(cat "$WATCHER")" = "$(watcher_content)" ] \
    && [ "$(cat "$DAEMON")" = "$(daemon_content)" ] \
    && [ "$(cat "$UNIT_DIR/$UNIT_NAME")" = "$(unit_content)" ]; then
      ok "installed files match what this script generates"
    else
      fail "installed files have DRIFTED from this script -- re-run enable"
    fi
  fi

  [ -r "$PATTERNS_FILE" ] && ok "watch list present ($(grep -cvE '^\s*#|^\s*$' "$PATTERNS_FILE") pattern(s))" \
                          || fail "$PATTERNS_FILE missing -- nothing is watched"
  [ -r "$EXCLUDES_FILE" ] && ok "excludes present -- the watch can actually turn off" \
                          || fail "$EXCLUDES_FILE missing: Claude's idle daemon pool would satisfy the watch forever"

  # --- KDE must be out of the suspend business -------------------------
  local section bad_lid=0 bad_idle=0
  if [ -f "$KDE_PROFILES" ]; then
    for section in $KDE_PROFILE_SECTIONS; do
      [ "$(kde_get "[$section][HandleButtonEvents]" lidAction)" = "$LID_ACTION_BLANK" ] || bad_lid=1
      kde_has_group "[$section][SuspendSession]" && bad_idle=1
    done
    [ "$bad_lid" -eq 0 ] && ok "lidAction=$LID_ACTION_BLANK (turn off screen) in every profile" \
                         || fail "a profile's lidAction is not $LID_ACTION_BLANK -- PowerDevil may suspend the lid itself"
    [ "$bad_idle" -eq 0 ] && ok "no [*][SuspendSession] -- idle autosuspend is off in every profile" \
                          || fail "a profile still has SuspendSession -- PowerDevil can idle-suspend behind this daemon"
  else
    skip "$KDE_PROFILES absent -- not a KDE session?"
  fi

  if [ "$LIVE" -eq 1 ]; then
    systemctl --user is-active --quiet "$UNIT_NAME" \
      && ok "$UNIT_NAME is running" \
      || fail "$UNIT_NAME is NOT running -- nothing is watching the lid, so nothing suspends"
  fi

  # The lid switch is load-bearing now, not just the beep.
  if id -nG 2>/dev/null | tr ' ' '\n' | grep -qx input; then
    ok "group 'input' held -- the daemon can read the lid switch"
  else
    fail "not in group 'input' -- the daemon cannot read the lid switch, so NOTHING suspends (sudo usermod -aG input $TARGET_USER)"
  fi

  # --- OUTCOMES: what lid closes actually did --------------------------
  if ! command -v journalctl >/dev/null 2>&1; then
    skip "no journalctl -- cannot read what lid closes actually did"
    finish_verify
  fi
  # Timestamps are epoch seconds (short-unix) so decisions and suspends
  # from separate queries can be matched by arithmetic.
  local ep_held ep_will_sleep ep_suspends
  ep_held="$(journalctl -b SYSLOG_IDENTIFIER=lid-inhibit-daemon --since '-7 days' -o short-unix --no-pager 2>/dev/null \
             | grep -F 'watch ACTIVE -- staying awake' | awk '{print int($1)}' || true)"
  ep_will_sleep="$(journalctl -b SYSLOG_IDENTIFIER=lid-inhibit-daemon --since '-7 days' -o short-unix --no-pager 2>/dev/null \
                   | grep -F 'suspending now' | awk '{print int($1)}' || true)"
  ep_suspends="$(journalctl -b -k --since '-7 days' -o short-unix --no-pager 2>/dev/null \
                 | grep -F 'PM: suspend entry' | awk '{print int($1)}' || true)"

  # A suspend within 90s after a decision is that decision's outcome
  # (immediate in practice; the margin covers the delay inhibitors --
  # NetworkManager, ModemManager, UPower -- unwinding).
  local d s
  within() { # $1 = decision epoch, $2 = window; reads $ep_suspends
    local c
    while IFS= read -r c; do
      [ -z "$c" ] && continue
      [ "$c" -ge "$1" ] && [ "$c" -le "$(($1 + $2))" ] && return 0
    done <<< "$ep_suspends"
    return 1
  }

  # FAILURE 1: held a close awake, and it suspended anyway. This is
  # exactly what killed attempt 2.
  local held=0 held_slept=0
  while IFS= read -r d; do
    [ -z "$d" ] && continue
    held=$((held + 1))
    within "$d" 90 && held_slept=$((held_slept + 1))
  done <<< "$ep_held"

  # FAILURE 2: decided to suspend, and nothing happened. This is
  # attempt 1's bug -- a remedy that never sleeps.
  local decided=0 decided_slept=0
  while IFS= read -r d; do
    [ -z "$d" ] && continue
    decided=$((decided + 1))
    within "$d" 90 && decided_slept=$((decided_slept + 1))
  done <<< "$ep_will_sleep"

  # FAILURE 3: something suspended us that this daemon never decided on.
  # PowerDevil, logind, or anything else still holding the lid. None of
  # the installation checks above can see this.
  local total_suspends=0 unexplained=0
  while IFS= read -r s; do
    [ -z "$s" ] && continue
    total_suspends=$((total_suspends + 1))
    local explained=0 c
    while IFS= read -r c; do
      [ -z "$c" ] && continue
      [ "$s" -ge "$c" ] && [ "$s" -le "$((c + 90))" ] && explained=1
    done <<< "$ep_will_sleep"
    [ "$explained" -eq 0 ] && unexplained=$((unexplained + 1))
  done <<< "$ep_suspends"

  note "journal (this boot): $held close(s) held awake, $decided suspend decision(s), $total_suspends actual suspend(s)"

  if [ "$held" -eq 0 ]; then
    skip "no lid close happened with the watch active -- close the lid ~15s with Claude running (expect the SHARP beep)"
  elif [ "$held_slept" -gt 0 ]; then
    fail "$held_slept of $held held close(s) suspended anyway -- work was interrupted; something other than this daemon still acts on the lid"
  else
    ok "$held close(s) held awake, none suspended"
  fi

  if [ "$decided" -eq 0 ]; then
    skip "no lid close happened with the watch quiet -- close the lid with nothing running (expect the DESCENDING beep, then sleep)"
  elif [ "$decided_slept" -lt "$decided" ]; then
    fail "$((decided - decided_slept)) of $decided suspend decision(s) did NOT reach a kernel suspend -- the lid does nothing at all"
  else
    ok "every suspend decision ($decided) reached a real kernel suspend"
  fi

  if [ "$unexplained" -gt 0 ]; then
    fail "$unexplained of $total_suspends suspend(s) were not decided by this daemon -- PowerDevil or logind is still suspending behind it"
  elif [ "$total_suspends" -gt 0 ]; then
    ok "every suspend this boot was decided by this daemon"
  fi

  finish_verify "OK -- the lid blanks, and only this daemon suspends."
}

parse_common_args "$@"
case "${1:-}" in
  enable)  enable_ ;;
  disable) disable_ ;;
  verify)  verify_ ;;
  *) die "usage: $(basename "$0") enable|disable|verify" ;;
esac
