#!/usr/bin/env bash
# senechal: audit EVERY desktop notification firing on the session bus,
# not just senechal's own -- so a spam channel from an unrelated sender
# is visible instead of invisible.
#
#   [rest: vault:senechal/header-archaeology-20260818.md]
set -uo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"
# shellcheck source=../lib/common.sh
. ../lib/common.sh

DAEMON="$HOME/.local/bin/senechal-notify-audit-daemon"
UNIT_NAME="senechal-notify-audit.service"
# Overridable for tests only: lets `enable` run against a throwaway
# HOME with no live systemd.
UNIT_DIR="${SENECHAL_NOTIFY_AUDIT_UNIT_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user}"
LOG="${XDG_STATE_HOME:-$HOME/.local/state}/senechal/notify-audit.log"
LIVE=1
[ -z "${SENECHAL_NOTIFY_AUDIT_UNIT_DIR:-}" ] || LIVE=0

# Self-contained on purpose, like lid-inhibit-daemon next to it: this
# runs from $HOME, independent of the checkout that installed it, so a
# moved/removed senechal checkout does not silently kill a live daemon.
daemon_content() {
  cat <<'EOF'
#!/usr/bin/env bash
# senechal-notify-audit-daemon -- generated by remedies/notify-audit.sh,
# do not hand-edit (re-run enable instead). Listens on the session D-Bus
# bus for EVERY org.freedesktop.Notifications.Notify call -- any sender,
#   [rest: vault:senechal/header-archaeology-20260818.md]
set -uo pipefail
LOG="${XDG_STATE_HOME:-$HOME/.local/state}/senechal/notify-audit.log"
mkdir -p "$(dirname "$LOG")"

exec dbus-monitor --session "interface='org.freedesktop.Notifications',member='Notify'" \
  | awk -v logfile="$LOG" '
      # Notify(app_name STRING, replaces_id UINT32, app_icon STRING,
      # summary STRING, body STRING, actions ARRAY, hints DICT,
      # expire_timeout INT32) -- of the STRING-typed args in order, the
      # 1st is app_name and the 3rd is summary; replaces_id (uint32) is
      # not string-typed so it never advances this count.
      /^method call .*member=Notify$/ { capturing = 1; n = 0; next }
      capturing && /^[[:space:]]*string / {
        n++
        line = $0
        sub(/^[[:space:]]*string "/, "", line)
        sub(/"[[:space:]]*$/, "", line)
        if (n == 1) app = line
        if (n == 3) {
          "date +%Y-%m-%dT%H:%M:%S%z" | getline ts
          close("date +%Y-%m-%dT%H:%M:%S%z")
          gsub(/\t/, " ", app); gsub(/\t/, " ", line)
          print ts "\t" app "\t" line >> logfile
          fflush(logfile)
          capturing = 0
        }
      }
    '
EOF
}

unit_content() {
  cat <<EOF
[Unit]
Description=senechal: audit every desktop notification (not just senechal's own)

[Service]
ExecStart=$DAEMON
Restart=always

[Install]
WantedBy=default.target
EOF
}

install_file() { # $1 dest, $2 mode, content on stdin
  local dest="$1" mode="$2" content b
  content="$(cat)"
  if [ -f "$dest" ] && [ "$(cat "$dest" 2>/dev/null)" = "$content" ]; then
    say "  $dest -- already correct, untouched"
    chmod "$mode" "$dest"
    return 0
  fi
  b="$(backup_file "$dest")" && [ -n "$b" ] && say "  backed up old $dest -> $b"
  mkdir -p "$(dirname "$dest")" || die "could not create $(dirname "$dest")"
  printf '%s\n' "$content" > "$dest" || die "could not write $dest"
  chmod "$mode" "$dest"
  say "  wrote $dest"
}

# --- enable ---------------------------------------------------------------
enable_() {
  say "notify-audit enable: log every desktop notification, any sender"
  command -v dbus-monitor >/dev/null 2>&1 \
    || die "dbus-monitor not found -- install dbus (apt install dbus)"

  daemon_content | install_file "$DAEMON" 0755
  unit_content   | install_file "$UNIT_DIR/$UNIT_NAME" 0644

  if [ "$LIVE" -eq 1 ]; then
    systemctl --user daemon-reload || die "daemon-reload failed"
    systemctl --user enable --now "$UNIT_NAME" || die "could not enable $UNIT_NAME"
    say "  $UNIT_NAME enabled and started"
  else
    say "  (test mode: skipped daemon-reload / enable)"
  fi

  say ""
  say "Done. health/estate-health.sh's check_notify_audit reads and clears"
  say "$LOG every hourly run -- see MUTED-CHECKS.md if it never seems to fire."
  say "Test it by hand: notify-send 'audit test' 'hello' ; sleep 1 ; cat '$LOG'"
}

# --- disable ----------------------------------------------------------------
disable_() {
  say "notify-audit disable: stop logging notifications"
  if [ "$LIVE" -eq 1 ]; then
    systemctl --user disable --now "$UNIT_NAME" 2>/dev/null || say "  (unit was not enabled)"
  fi
  say "Done. $DAEMON left in place; delete it by hand if you want it gone."
}

# --- verify -----------------------------------------------------------------
verify_() {
  head_ "notify-audit: every desktop notification logged, any sender"

  [ -f "$DAEMON" ] || { fail "$DAEMON missing -- run: ./notify-audit.sh enable"; finish_verify; }
  [ "$(cat "$DAEMON")" = "$(daemon_content)" ] \
    && ok "$DAEMON matches this script" \
    || fail "$DAEMON drifted from this script -- re-run enable"

  [ -f "$UNIT_DIR/$UNIT_NAME" ] || { fail "$UNIT_DIR/$UNIT_NAME missing -- run enable"; finish_verify; }
  [ "$(cat "$UNIT_DIR/$UNIT_NAME")" = "$(unit_content)" ] \
    && ok "$UNIT_NAME matches this script" \
    || fail "$UNIT_NAME drifted from this script -- re-run enable"

  if [ "$LIVE" -ne 1 ]; then
    skip "test mode -- no live systemd to ask about $UNIT_NAME"
    finish_verify
  fi

  # A --user service needs a session bus to be asked about at all.
  if ! systemctl --user show-environment >/dev/null 2>&1; then
    skip "no user session bus reachable (cron/ssh context) -- cannot ask whether $UNIT_NAME is running"
    finish_verify
  fi

  systemctl --user is-active --quiet "$UNIT_NAME" 2>/dev/null \
    && ok "$UNIT_NAME is active" \
    || fail "$UNIT_NAME not active -- systemctl --user start $UNIT_NAME"

  # Evidence, not just intent -- same "read the outcome, not the config"
  # rule as lid-inhibit-honoured's own verify.
  local hist="${XDG_STATE_HOME:-$HOME/.local/state}/senechal/notify-audit-history.tsv"
  if [ -r "$hist" ] && [ -s "$hist" ]; then
    ok "notify-audit-history.tsv has $(grep -c . "$hist") summarised run(s), last: $(tail -n1 "$hist" | cut -f1-2 | tr '\t' ' ')"
  elif [ -r "$LOG" ] && [ -s "$LOG" ]; then
    ok "raw log has entries, awaiting the next hourly summarize-and-clear"
  else
    skip "no entries logged or summarised yet -- give it time, or fire a test notification: notify-send test test"
  fi

  finish_verify "OK -- notify-audit is running and logging."
}

case "${1:-}" in
  enable)  enable_ ;;
  disable) disable_ ;;
  verify)  verify_ ;;
  *) die "usage: $(basename "$0") enable|disable|verify" ;;
esac
