#!/usr/bin/env bash
# senechal: flap-guard the notify-send CHANNEL ITSELF, for every sender on
# this host -- not just senechal's own alerts.
#
#   ./notify-send-flap-guard.sh enable    # install the wrapper
#   [rest: vault:senechal/header-archaeology-20260818.md]
set -uo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"
# shellcheck source=../lib/common.sh
. ../lib/common.sh

WRAPPER="$HOME/.local/bin/notify-send"
STATE_DIR="$(senechal_state_dir)/notify-flap-guard"

wrapper_content() {
  cat <<'EOF'
#!/usr/bin/env bash
# senechal-notify-send-flap-guard -- generated by
# remedies/notify-send-flap-guard.sh, do not hand-edit (re-run enable
# instead). Shadows the real notify-send: an identical (summary+body)
#   [rest: vault:senechal/header-archaeology-20260818.md]
set -uo pipefail

# Overridable for tests only: lets a scratch HOME point this at a stub
# binary instead of the real system notify-send.
REAL="${SENECHAL_NOTIFY_SEND_REAL:-}"
if [ -z "$REAL" ]; then
  for d in /usr/bin /bin /usr/local/bin; do
    [ -x "$d/notify-send" ] && { REAL="$d/notify-send"; break; }
  done
fi
[ -n "$REAL" ] && [ -x "$REAL" ] || { echo "notify-send: no real binary found on this host" >&2; exit 1; }

STATE="${XDG_STATE_HOME:-$HOME/.local/state}/senechal/notify-flap-guard"
mkdir -p "$STATE" 2>/dev/null || true

COOLDOWN="${SENECHAL_NOTIFY_FLAP_COOLDOWN:-300}"        # seconds
EXPIRE_MS="${SENECHAL_NOTIFY_FLAP_EXPIRE_MS:-3600000}"  # 60 min, only if caller didn't pass -t

# Minimal arg walk: we only need to know whether the caller already
# passed -r/--replace-id or -t/--expire-time, and what SUMMARY/BODY are
# (the last one or two non-flag positionals) -- not a full notify-send
# CLI reimplementation.
has_replace=0
has_expire=0
positional=()
i=0
args=("$@")
n=${#args[@]}
while [ $i -lt $n ]; do
  a="${args[$i]}"
  case "$a" in
    -r|--replace-id) has_replace=1; i=$((i+2)) ;;
    --replace-id=*)  has_replace=1; i=$((i+1)) ;;
    -t|--expire-time) has_expire=1; i=$((i+2)) ;;
    --expire-time=*)  has_expire=1; i=$((i+1)) ;;
    -u|--urgency|-i|--icon|-c|--category|-h|--hint|-a|--app-name)
      i=$((i+2)) ;;
    -*) i=$((i+1)) ;;
    *) positional+=("$a"); i=$((i+1)) ;;
  esac
done

summary="${positional[0]:-}"
body="${positional[1]:-}"

# Nothing to key on (e.g. --help, -l) -- pass straight through.
if [ -z "$summary" ]; then
  exec "$REAL" "$@"
fi

key="$(printf '%s' "$summary" | cksum | cut -d' ' -f1)"
msgfile="$STATE/$key.msg"
tsfile="$STATE/$key.ts"
idfile="$STATE/$key.id"
suppressed_file="$STATE/suppressed-count"

now="$(date +%s)"
last_msg="$(cat "$msgfile" 2>/dev/null || echo '')"
last_ts="$(cat "$tsfile" 2>/dev/null || echo 0)"
case "$last_ts" in ''|*[!0-9]*) last_ts=0 ;; esac
cur_msg="$summary"$'\x1e'"$body"

if [ "$cur_msg" = "$last_msg" ] && [ $((now - last_ts)) -lt "$COOLDOWN" ]; then
  c="$(cat "$suppressed_file" 2>/dev/null || echo 0)"
  case "$c" in ''|*[!0-9]*) c=0 ;; esac
  echo $((c + 1)) > "$suppressed_file" 2>/dev/null || true
  exit 0
fi

extra=()
if [ "$has_replace" -eq 0 ]; then
  last_id="$(cat "$idfile" 2>/dev/null || echo 0)"
  case "$last_id" in ''|*[!0-9]*) last_id=0 ;; esac
  extra+=(-r "$last_id")
fi
if [ "$has_expire" -eq 0 ]; then
  extra+=(-t "$EXPIRE_MS")
fi

new_id="$("$REAL" "${extra[@]}" "$@" 2>/dev/null)"
rc=$?
printf '%s\n' "$cur_msg" > "$msgfile" 2>/dev/null || true
printf '%s\n' "$now" > "$tsfile" 2>/dev/null || true
case "$new_id" in ''|*[!0-9]*) ;; *) printf '%s\n' "$new_id" > "$idfile" 2>/dev/null || true ;; esac
[ -n "$new_id" ] && printf '%s\n' "$new_id"
exit "$rc"
EOF
}

install_file() { # $1 dest, $2 mode, content on stdin
  local dest="$1" mode="$2" content b
  content="$(cat)"
  if [ -f "$dest" ] && [ "$(cat "$dest" 2>/dev/null)" = "$content" ]; then
    say "  $dest -- already correct, untouched"
    chmod "$mode" "$dest"
    return 0
  fi
  b="$(backup_file "$dest")" && [ -n "$b" ] && say "  backed up old $dest -> $b"
  mkdir -p "$(dirname "$dest")" || die "could not create $(dirname "$dest")"
  printf '%s\n' "$content" > "$dest" || die "could not write $dest"
  chmod "$mode" "$dest"
  say "  wrote $dest"
}

# --- enable ---------------------------------------------------------------
enable_() {
  say "notify-send-flap-guard enable: shadow notify-send for every sender"

  local real="${SENECHAL_NOTIFY_SEND_REAL:-}"
  if [ -z "$real" ]; then
    for d in /usr/bin /bin /usr/local/bin; do
      [ -x "$d/notify-send" ] && { real="$d/notify-send"; break; }
    done
  fi
  [ -n "$real" ] && [ -x "$real" ] || die "no real notify-send found on this host -- nothing to wrap"

  wrapper_content | install_file "$WRAPPER" 0755
  mkdir -p "$STATE_DIR" || say "  (warning: could not pre-create $STATE_DIR -- wrapper will retry per-call)"

  say ""
  if command -v notify-send >/dev/null 2>&1 && [ "$(command -v notify-send)" = "$WRAPPER" ]; then
    say "Done. \`notify-send\` now resolves to $WRAPPER (PATH order confirmed)."
  else
    say "WROTE $WRAPPER, but it does not currently win PATH resolution"
    say "(command -v notify-send -> $(command -v notify-send 2>/dev/null || echo 'not found'))."
    say "~/.local/bin must come before $real's directory in PATH -- check ~/.bashrc."
  fi
  say "Test it by hand: notify-send 'flap test' 'one' ; notify-send 'flap test' 'one' ; echo suppressed=\$(cat '$STATE_DIR'/*.msg 2>/dev/null | wc -l)"
}

# --- disable ----------------------------------------------------------------
disable_() {
  say "notify-send-flap-guard disable: restore plain notify-send"
  if [ -f "$WRAPPER" ]; then
    rm -f "$WRAPPER"
    say "  removed $WRAPPER"
  else
    say "  (already absent)"
  fi
  say "Done. State under $STATE_DIR left in place; delete it by hand if you want it gone."
}

# --- verify -----------------------------------------------------------------
verify_() {
  head_ "notify-send-flap-guard: every sender's notify-send is deduped and tile-replacing"

  [ -f "$WRAPPER" ] || { fail "$WRAPPER missing -- run: ./notify-send-flap-guard.sh enable"; finish_verify; }
  [ "$(cat "$WRAPPER")" = "$(wrapper_content)" ] \
    && ok "$WRAPPER matches this script" \
    || fail "$WRAPPER drifted from this script -- re-run enable"
  [ -x "$WRAPPER" ] \
    && ok "$WRAPPER is executable" \
    || fail "$WRAPPER is not executable -- re-run enable"

  if command -v notify-send >/dev/null 2>&1; then
    if [ "$(command -v notify-send)" = "$WRAPPER" ]; then
      ok "PATH resolves notify-send to the flap-guard wrapper"
    else
      fail "PATH resolves notify-send to $(command -v notify-send), not $WRAPPER -- fix ~/.local/bin's PATH order"
    fi
  else
    skip "no notify-send on PATH at all -- cannot confirm resolution order"
  fi

  local suppressed_file="$STATE_DIR/suppressed-count"
  if [ -r "$suppressed_file" ]; then
    ok "flap guard has suppressed $(cat "$suppressed_file") duplicate notification(s) since last reset"
  else
    skip "no suppressions recorded yet -- give it time, or fire a test pair: notify-send t t; notify-send t t"
  fi

  finish_verify "OK -- notify-send-flap-guard is in effect for every sender."
}

case "${1:-}" in
  enable)  enable_ ;;
  disable) disable_ ;;
  verify)  verify_ ;;
  *) die "usage: $(basename "$0") enable|disable|verify" ;;
esac
